#!/usr/bin/python3
# -*- coding: utf-8 -*-

import sqlite3
import os
import re

# Chemin vers le fichier script HSQLDB
script_file = r"C:\Users\Baptiste\Downloads\script"
sqlite_file = r"C:\Users\Baptiste\Desktop\team_2.db"

conn = sqlite3.connect(sqlite_file)
c = conn.cursor()

# Fonction simple pour convertir les types HSQLDB -> SQLite
def convert_type(hsql_type):
  hsql_type = hsql_type.upper()
  if "VARCHAR" in hsql_type or "CHAR" in hsql_type:
    return "TEXT"
  elif "INT" in hsql_type:
    return "INTEGER"
  elif "DATE" in hsql_type or "TIMESTAMP" in hsql_type:
    return "TEXT"
  elif "BOOLEAN" in hsql_type:
    return "INTEGER"
  else:
    return "TEXT"

with open(script_file, "r", encoding="ISO-8859-1") as f:
  for line in f:
    line = line.strip()
    if line.startswith("CREATE TABLE"):
      # Conversion simple pour SQLite : enlever GENERATED BY DEFAULT, etc.
      line = re.sub(r"GENERATED BY DEFAULT AS IDENTITY", "", line)
      line = re.sub(r"BIGINT", "INTEGER", line)
      line = re.sub(r"VARCHAR\(\d+\)", "TEXT", line)
      line = re.sub(r"BOOLEAN", "INTEGER", line)
      try:
        c.execute(line)
      except sqlite3.OperationalError as e:
        print("Erreur CREATE TABLE:", e)
    elif line.startswith("INSERT INTO"):
      # Insérer directement dans SQLite
      try:
        c.execute(line)
      except sqlite3.OperationalError as e:
        print("Erreur INSERT:", e)

conn.commit()
conn.close()
print("Conversion HSQLDB -> SQLite terminée, fichier créé:", sqlite_file)